on:
  discussion:
    types: [ created, edited ]

jobs:
  discussions:
    runs-on: ubuntu-latest
    name: Writes discussions to file
    steps:
      - name: Write discussions step
        id: write_discussions
        uses: peterhenryd/write-discussions-to-repo-action@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo-owner: "peterhenryd"
          repo-name: "peterhenryd-me"
          query-fields: "title id url"
          output-path: "data/discussions/urls.json"
